
/* Auto-generated by tools/harp_wrap.py — do not edit.
 * Sequence: longlive_seq.S  (8 lines x 200 iter(s))
 * Deterministic wrapper for Harpocrates coverage evaluation (gem5 SE).
 * Register state flows through g_reg[] (memory), per the clobber-list
 * design (GCC 12 caps a single asm at 30 operands; 20 "+r" outputs
 * exceed it — measured, see header comment of harp_wrap.py).
 */
#include <stdio.h>
#include <stdint.h>
#include <string.h>

#define MEM_BYTES   32768
#define MEM_ELEMS   (MEM_BYTES / 8)
#define NREGS       20
#define ITERS       200

static uint64_t g_reg[NREGS];            /* X9-X28 进/出 asm 的通道 */
static uint64_t mem[MEM_ELEMS] __attribute__((aligned(64)));

/* xorshift64 确定性生成器（与 sdc_probe_workload_evolved.c 同款） */
static uint64_t xs1 = 10741317929018119496ULL;
static uint64_t xs2 = 11943854631887459438ULL;
static uint64_t xs64(void)
{
    uint64_t s1 = xs1, s2 = xs2 ^ (xs2 << 23);
    xs1 = s2; xs2 = s1 ^ (s1 >> 17) ^ (s2 >> 26);
    return xs1 + s2;
}

static uint32_t crc32(const void *buf, size_t n)
{
    const uint8_t *p = (const uint8_t *)buf;
    uint32_t crc = 0xFFFFFFFFu;
    for (size_t i = 0; i < n; i++) {
        crc ^= p[i];
        for (int k = 0; k < 8; k++)
            crc = (crc >> 1) ^ (0xEDB88320u & (uint32_t)-(int32_t)(crc & 1));
    }
    return crc ^ 0xFFFFFFFFu;
}

static inline void m5_workbegin(void)
{
#if WITH_M5OPS
    register uint64_t x0 __asm__("x0") = 1, x1 __asm__("x1") = 0;
    __asm__ volatile(".inst 0xff5a0110" : "+r"(x0) : "r"(x1) : "memory");
#endif
}
static inline void m5_workend(void)
{
#if WITH_M5OPS
    register uint64_t x0 __asm__("x0") = 1, x1 __asm__("x1") = 0;
    __asm__ volatile(".inst 0xff5b0110" : "+r"(x0) : "r"(x1) : "memory");
#endif
}

int main(void)
{
    /* --- 1. 确定性初始化：寄存器组（g_reg）与内存 --- */
    for (int i = 0; i < NREGS; i++)
        g_reg[i] = xs64();
    for (int i = 0; i < MEM_ELEMS; i++)
        mem[i] = xs64();

    /* --- 2. warmup（论文：让核心序列在相似硬件状态下执行）--- */
    { uint64_t w = 0; for (int i = 0; i < 64; i++) w += xs64(); (void)w; }

    /* --- 3. ROI 标记 + 核心序列（单 asm 大块，保序）--- */
    m5_workbegin();
    for (int it = 0; it < ITERS; it++) {
__asm__ volatile (
    /* 载入寄存器初值（g_reg[0..19] -> x9..x28） */
    "ldr x9, [%[regs], #0]   \n\t"
    "ldr x10, [%[regs], #8]   \n\t"
    "ldr x11, [%[regs], #16]   \n\t"
    "ldr x12, [%[regs], #24]   \n\t"
    "ldr x13, [%[regs], #32]   \n\t"
    "ldr x14, [%[regs], #40]   \n\t"
    "ldr x15, [%[regs], #48]   \n\t"
    "ldr x16, [%[regs], #56]   \n\t"
    "ldr x17, [%[regs], #64]   \n\t"
    "ldr x18, [%[regs], #72]   \n\t"
    "ldr x19, [%[regs], #80]   \n\t"
    "ldr x20, [%[regs], #88]   \n\t"
    "ldr x21, [%[regs], #96]   \n\t"
    "ldr x22, [%[regs], #104]   \n\t"
    "ldr x23, [%[regs], #112]   \n\t"
    "ldr x24, [%[regs], #120]   \n\t"
    "ldr x25, [%[regs], #128]   \n\t"
    "ldr x26, [%[regs], #136]   \n\t"
    "ldr x27, [%[regs], #144]   \n\t"
    "ldr x28, [%[regs], #152]   \n\t"
    /* ==== 核心指令序列（longlive_seq.S）==== */
    "add x9, x9, x9   \n\t"
    "add x10, x10, x10   \n\t"
    "add x11, x11, x11   \n\t"
    "add x12, x12, x12   \n\t"
    "add x13, x13, x13   \n\t"
    "add x14, x14, x14   \n\t"
    "add x15, x15, x15   \n\t"
    "add x16, x16, x16   \n\t"
    /* 存回寄存器终态（x9..x28 -> g_reg[0..19]） */
    "str x9, [%[regs], #0]   \n\t"
    "str x10, [%[regs], #8]   \n\t"
    "str x11, [%[regs], #16]   \n\t"
    "str x12, [%[regs], #24]   \n\t"
    "str x13, [%[regs], #32]   \n\t"
    "str x14, [%[regs], #40]   \n\t"
    "str x15, [%[regs], #48]   \n\t"
    "str x16, [%[regs], #56]   \n\t"
    "str x17, [%[regs], #64]   \n\t"
    "str x18, [%[regs], #72]   \n\t"
    "str x19, [%[regs], #80]   \n\t"
    "str x20, [%[regs], #88]   \n\t"
    "str x21, [%[regs], #96]   \n\t"
    "str x22, [%[regs], #104]   \n\t"
    "str x23, [%[regs], #112]   \n\t"
    "str x24, [%[regs], #120]   \n\t"
    "str x25, [%[regs], #128]   \n\t"
    "str x26, [%[regs], #136]   \n\t"
    "str x27, [%[regs], #144]   \n\t"
    "str x28, [%[regs], #152]   \n\t"
    :
    : [regs] "r" (g_reg), [base] "r" (mem)
    : "memory", "x9", "x10", "x11", "x12", "x13", "x14", "x15", "x16", "x17", "x18", "x19", "x20", "x21", "x22", "x23", "x24", "x25", "x26", "x27", "x28", "v8", "v9", "v10", "v11", "v12", "v13", "v14", "v15"
);
    }
    m5_workend();

    /* --- 4. epilogue 签名：寄存器终态哈希 + 内存 CRC --- */
    uint64_t sum = 0;
    for (int i = 0; i < NREGS; i++)
        sum = sum * 1315423911u + g_reg[i];
    uint32_t crc = crc32(mem, sizeof(mem));
    printf("SUM=%llu CRC=%08x\n", (unsigned long long)sum, crc);
    return 0;
}
