#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""harp_wrap.py — Harpocrates 覆盖评估的指令序列包装生成器（计划 Task 1.1）。

对应论文（Harpocrates ISCA'24 §V-D / Micro'26）的 MuSeqGen wrapper 功能：
把"给定的指令流序列"包装成确定性、可被 gem5 SE 仿真的 aarch64 静态 ELF：
  1. 寄存器/内存确定性初始化（固定种子 xorshift64，无 libc 随机态）
  2. m5ops ROI 标记（workbegin/workend = 0xff5a0110/0xff5b0110，
     编码实证见 tools/harp_roi_spike.c —— func 必须在 bits 23:16）
  3. 核心序列：单条 __asm__ volatile 大块（保序），X9-X28 全部列入
     clobber（GCC 12 单 asm 30 操作数上限 → 不能用 +r 操作数传递，
     寄存器初值/终态经全局数组 g_reg[] 内存进出，t14 实测方案）
  4. epilogue 签名：X0-X30 终态（g_reg 求和哈希）+ 内存区域 CRC
     （论文 deterministic output = 寄存器终态 + 内存签名），printf 单行

输入格式（三选一）：
  (a) 现成 aarch64 静态 ELF：--seq path/to/elf --pass-through
  (b) .S 汇编片段：每行一条 AArch64 指令（白名单助记符，无标号/伪指令）
  (c) --random 随机序列（Task 7.2 基线，论文 Generator 第 0 代）

用法示例：
  python3 tools/harp_wrap.py --seq workloads/harp/seq.S --out workloads/harp/seq
  python3 tools/harp_wrap.py --random --n-inst 5000 --mix int-heavy \
      --out workloads/harp/rand5k
  python3 tools/harp_wrap.py --seq old.elf --pass-through --out workloads/harp/

论文参数对齐（findings.md"程序参数"节）：
  IRF 10K / L1D 30K / FU 5K 指令预算；L1D 用 32KB 区域 stride 8B
"""
import argparse
import os
import re
import subprocess
import sys

# m5ops 编码（tools/harp_roi_spike.c 实测：func 在 bits 23:16）
M5_WORKBEGIN = 0xff5a0110
M5_WORKEND = 0xff5b0110

# 核心序列可用的 GPR（X9-X28，caller-saved，不碰 SP/FP/LR/X8-）
# X8 留作内存操作数 base（t14 方案），X0-X7 留给 ABI
SEQ_REGS = list(range(9, 29))  # [x9..x28]
REG_NAMES = [f"x{i}" for i in SEQ_REGS]

WRAPPER_TEMPLATE = r'''
/* Auto-generated by tools/harp_wrap.py — do not edit.
 * Sequence: {seq_name}  ({n_lines} lines x {iters} iter(s))
 * Deterministic wrapper for Harpocrates coverage evaluation (gem5 SE).
 * Register state flows through g_reg[] (memory), per the clobber-list
 * design (GCC 12 caps a single asm at 30 operands; 20 "+r" outputs
 * exceed it — measured, see header comment of harp_wrap.py).
 */
#include <stdio.h>
#include <stdint.h>
#include <string.h>

#define MEM_BYTES   {mem_bytes}
#define MEM_ELEMS   (MEM_BYTES / 8)
#define NREGS       {nregs}
#define ITERS       {iters}

static uint64_t g_reg[NREGS];            /* X9-X28 进/出 asm 的通道 */
static uint64_t mem[MEM_ELEMS] __attribute__((aligned(64)));

/* xorshift64 确定性生成器（与 sdc_probe_workload_evolved.c 同款） */
static uint64_t xs1 = {xs1}ULL;
static uint64_t xs2 = {xs2}ULL;
static uint64_t xs64(void)
{{
    uint64_t s1 = xs1, s2 = xs2 ^ (xs2 << 23);
    xs1 = s2; xs2 = s1 ^ (s1 >> 17) ^ (s2 >> 26);
    return xs1 + s2;
}}

static uint32_t crc32(const void *buf, size_t n)
{{
    const uint8_t *p = (const uint8_t *)buf;
    uint32_t crc = 0xFFFFFFFFu;
    for (size_t i = 0; i < n; i++) {{
        crc ^= p[i];
        for (int k = 0; k < 8; k++)
            crc = (crc >> 1) ^ (0xEDB88320u & (uint32_t)-(int32_t)(crc & 1));
    }}
    return crc ^ 0xFFFFFFFFu;
}}

static inline void m5_workbegin(void)
{{
#if WITH_M5OPS
    register uint64_t x0 __asm__("x0") = 1, x1 __asm__("x1") = 0;
    __asm__ volatile(".inst 0x{wb:x}" : "+r"(x0) : "r"(x1) : "memory");
#endif
}}
static inline void m5_workend(void)
{{
#if WITH_M5OPS
    register uint64_t x0 __asm__("x0") = 1, x1 __asm__("x1") = 0;
    __asm__ volatile(".inst 0x{we:x}" : "+r"(x0) : "r"(x1) : "memory");
#endif
}}

int main(void)
{{
    /* --- 1. 确定性初始化：寄存器组（g_reg）与内存 --- */
    for (int i = 0; i < NREGS; i++)
        g_reg[i] = xs64();
    for (int i = 0; i < MEM_ELEMS; i++)
        mem[i] = xs64();

    /* --- 2. warmup（论文：让核心序列在相似硬件状态下执行）--- */
    {{ uint64_t w = 0; for (int i = 0; i < 64; i++) w += xs64(); (void)w; }}

    /* --- 3. ROI 标记 + 核心序列（单 asm 大块，保序）--- */
    m5_workbegin();
    for (int it = 0; it < ITERS; it++) {{
__asm__ volatile (
    /* 载入寄存器初值（g_reg[0..19] -> x9..x28） */
{load_body}
    /* ==== 核心指令序列（{seq_name}）==== */
{asm_body}
    /* 存回寄存器终态（x9..x28 -> g_reg[0..19]） */
{store_body}
    :
    : [regs] "r" (g_reg), [base] "r" (mem)
    : "memory"{clobbers}
);
    }}
    m5_workend();

    /* --- 4. epilogue 签名：寄存器终态哈希 + 内存 CRC --- */
    uint64_t sum = 0;
    for (int i = 0; i < NREGS; i++)
        sum = sum * 1315423911u + g_reg[i];
    uint32_t crc = crc32(mem, sizeof(mem));
    printf("SUM=%llu CRC=%08x\n", (unsigned long long)sum, crc);
    return 0;
}}
'''

# SDC-ED Task 7.1 部署模式 checker 模板（--checker）：同核复算——核心
# 序列跑两遍（第二遍用影子内存 mem2 与影子寄存器数组 g_reg2），epilogue
# 比对两份签名。无 golden 对照：检测 = 两次执行不一致（CHECKER=FAIL）。
# 结构性弱点如实入文档：permanent FU 故障若两次执行都走同一 FU 则两次
# 同样腐蚀 → 漏检——同核复算对 permanent 的失效是该臂要量化的部署态
# 缺陷（对照 transient 单次翻转天然只腐蚀一遍）。
CHECKER_TEMPLATE = '''
#include <stdio.h>
#include <stdint.h>
#include <string.h>

#define MEM_BYTES   {mem_bytes}
#define MEM_ELEMS   (MEM_BYTES / 8)
#define NREGS       {nregs}
#define ITERS       {iters}

static uint64_t g_reg[NREGS];
static uint64_t g_reg2[NREGS];
static uint64_t mem[MEM_ELEMS] __attribute__((aligned(64)));
static uint64_t mem2[MEM_ELEMS] __attribute__((aligned(64)));

static uint64_t xs1 = {xs1}ULL;
static uint64_t xs2 = {xs2}ULL;
static uint64_t xs64(void)
{{
    uint64_t s1 = xs1, s2 = xs2 ^ (xs2 << 23);
    xs1 = s2; xs2 = s1 ^ (s1 >> 17) ^ (s2 >> 26);
    return xs1 + s2;
}}

static uint32_t crc32(const void *buf, size_t n)
{{
    const uint8_t *p = (const uint8_t *)buf;
    uint32_t crc = 0xFFFFFFFFu;
    for (size_t i = 0; i < n; i++) {{
        crc ^= p[i];
        for (int k = 0; k < 8; k++)
            crc = (crc >> 1) ^ (0xEDB88320u & (uint32_t)(-(int32_t)(crc & 1)));
    }}
    return ~crc;
}}

#if WITH_M5OPS
static void m5_workbegin(void)
{{
    register uint64_t x0 __asm__("x0") = 1, x1 __asm__("x1") = 0;
    __asm__ volatile(".inst 0x{wb:x}" : "+r"(x0) : "r"(x1) : "memory");
}}
static void m5_workend(void)
{{
    register uint64_t x0 __asm__("x0") = 1, x1 __asm__("x1") = 0;
    __asm__ volatile(".inst 0x{we:x}" : "+r"(x0) : "r"(x1) : "memory");
}}
#else
static void m5_workbegin(void) {{}}
static void m5_workend(void) {{}}
#endif

int main(void)
{{
    /* 确定性初始化：两通道同种子 → 同初值（复算前提）*/
    for (int i = 0; i < NREGS; i++) {{
        uint64_t v = xs64();
        g_reg[i] = v; g_reg2[i] = v;
    }}
    for (int i = 0; i < MEM_ELEMS; i++) {{
        uint64_t v = xs64();
        mem[i] = v; mem2[i] = v;
    }}
    {{ uint64_t w = 0; for (int i = 0; i < 64; i++) w += xs64(); (void)w; }}

    m5_workbegin();
    for (int it = 0; it < ITERS; it++) {{
__asm__ volatile (
{load_body}
    /* ==== 核心指令序列 pass1（{seq_name}）==== */
{asm_body}
{store_body}
    :
    : [regs] "r" (g_reg), [base] "r" (mem)
    : "memory"{clobbers}
);
    }}
    for (int it = 0; it < ITERS; it++) {{
__asm__ volatile (
{load_body}
    /* ==== 核心指令序列 pass2（影子通道，{seq_name}）==== */
{asm_body}
{store_body}
    :
    : [regs] "r" (g_reg2), [base] "r" (mem2)
    : "memory"{clobbers}
);
    }}
    m5_workend();

    /* checker 判定（部署态——无 golden）*/
    uint64_t s1 = 0, s2 = 0;
    for (int i = 0; i < NREGS; i++) {{
        s1 = s1 * 1315423911u + g_reg[i];
        s2 = s2 * 1315423911u + g_reg2[i];
    }}
    uint32_t c1 = crc32(mem, sizeof(mem));
    uint32_t c2 = crc32(mem2, sizeof(mem2));
    printf("SUM1=%llu CRC1=%08x SUM2=%llu CRC2=%08x\\n",
           (unsigned long long)s1, c1, (unsigned long long)s2, c2);
    if (s1 != s2 || c1 != c2)
        printf("CHECKER=FAIL\\n");
    else
        printf("CHECKER=OK\\n");
    return 0;
}}
'''

# 指令池（Task 7.2 随机基线 + Task 6.2 盲变异共用）。
# ARM64 MUL 是三操作数（无 x86 MUL 隐式写 RAX 的 quirk）。
# FP 用 D 寄存器（64b double）；FP 初值从 g_reg 载入 v8-v15 需要额外
# 载入块 —— 为保持 wrapper 简单，FP 序列的初值经 ldr d-寄存器,[base]
# 从内存取，结果亦 str 回内存（写入签名）。
INST_POOL = {
    "int-heavy": [
        "add x9, x10, x11", "sub x12, x13, x14", "eor x15, x16, x17",
        "and x18, x19, x20", "orr x21, x22, x23", "bic x24, x25, x26",
        "eor x27, x28, x9", "add x10, x11, x12", "sub x13, x14, x15",
        "and x16, x17, x18", "mul x19, x20, x21", "mul x22, x23, x24",
        "add x25, x26, x27", "eor x28, x9, x10", "sub x11, x12, x13",
        "orr x14, x15, x16", "mul x17, x18, x19", "add x20, x21, x22",
    ],
    "fp-heavy": [
        "ldr d8, [x8, #0]", "ldr d9, [x8, #8]", "ldr d10, [x8, #16]",
        "fadd d8, d9, d10", "fmul d11, d8, d9", "fsub d12, d10, d11",
        "ldr d13, [x8, #24]", "fadd d13, d12, d11", "fmul d14, d13, d8",
        "str d14, [x8, #32]", "ldr d15, [x8, #40]", "fmul d15, d14, d13",
        "fadd d8, d15, d12", "str d8, [x8, #48]",
    ],
    "mem": [
        "ldr x9, [x8, #0]", "str x10, [x8, #8]", "ldr x11, [x8, #16]",
        "str x12, [x8, #24]", "ldr x13, [x8, #32]", "str x14, [x8, #40]",
        "ldr x15, [x8, #48]", "str x16, [x8, #56]", "ldr x17, [x8, #64]",
        "str x18, [x8, #72]", "ldr x19, [x8, #80]", "str x20, [x8, #88]",
    ],
    "balanced": [],  # 合成：60% int + 25% fp + 15% mem（运行时混合）
}

# 内存操作数 base 统一为 x8（wrapper 的 [base] 输入操作数注入 mem 地址）

# 指令白名单（防伪指令/分支/system 类破坏确定性与线性控制流）
MNEMONIC_WHITELIST = (
    "add ", "sub ", "eor ", "and ", "orr ", "bic ", "mul ", "neg ",
    "madd ", "mneg ", "mov ", "movk ", "movz ",
    "fadd ", "fsub ", "fmul ", "fneg ", "fabs ", "fmadd ",
    "ldr ", "str ",
)


def sanitize_asm_line(line, lineno):
    """校验一行指令：非空、无标号/伪指令/危险助记符。返回 (inst|None, err|None)。"""
    # 剥注释时保护 [x8, #imm] 里的 '#'（ARM 立即数偏移前缀）：
    # 只把方括号深度为 0 处的 '#...' 当注释（盲变异实验实测：
    # split("#") 把 'str x12,[x8, #24]' 截成 'str x12,[x8,' 使 gcc 报
    # invalid expression）。
    depth = 0
    cut = len(line)
    for i, ch in enumerate(line):
        if ch == '[':
            depth += 1
        elif ch == ']':
            depth -= 1
        elif ch == '#' and depth == 0:
            cut = i
            break
    s = line[:cut].split("//")[0].split(";")[0].strip()
    if not s or s.startswith("."):
        return None, None  # 空行/注释/伪指令 → 跳过
    if ":" in s:
        return None, f"line {lineno}: labels unsupported ('{line.strip()}')"
    if not any(s.startswith(p) for p in MNEMONIC_WHITELIST):
        return None, (f"line {lineno}: mnemonic not in whitelist "
                      f"('{line.strip()}')")
    # 内存指令 base 必须是 x8（wrapper 约定）
    if ("[" in s) and ("x8" not in s.split("[")[1].split("]")[0]):
        return None, (f"line {lineno}: memory base must be x8 "
                      f"('{line.strip()}')")
    return s, None


def gen_random_sequence(n, mix, rng):
    """随机序列（论文 Generator 第 0 代等价物）。返回指令列表。"""
    if mix == "balanced":
        lines = []
        for _ in range(n):
            u = rng.random()
            pool = (INST_POOL["int-heavy"] if u < 0.60 else
                    INST_POOL["fp-heavy"] if u < 0.85 else
                    INST_POOL["mem"])
            lines.append(pool[rng.randrange(len(pool))])
        return lines
    pool = INST_POOL[mix]
    return [pool[rng.randrange(len(pool))] for _ in range(n)]


def wrap_and_compile(seq_lines, out_path, seq_name, mem_bytes, iters,
                     seed1, seed2, with_m5ops=True, checker=False):
    """生成 wrapper C 并编译为静态 ELF。返回 (elf_path, c_path)。

    with_m5ops=False 时宏 WITH_M5OPS=0（本机可跑，无 ROI 标记）；
    两种构建的 SUM/CRC 必须一致（标记不碰 g_reg/mem）。
    """
    n = len(SEQ_REGS)
    # 载入块：g_reg[i] -> x{9+i}（基址 regs，偏移 8*i）
    load_body = "\n".join(
        f'    "ldr x{SEQ_REGS[i]}, [x8r, #{8 * i}]   \\n\\t"'
        for i in range(n))
    # 存回块：x{9+i} -> g_reg[i]
    store_body = "\n".join(
        f'    "str x{SEQ_REGS[i]}, [x8r, #{8 * i}]   \\n\\t"'
        for i in range(n))
    # core 序列（原样嵌入；FP/mem 指令已约定用 x8 做内存 base）
    asm_body = "\n".join(f'    "{l}   \\n\\t"' for l in seq_lines)
    # clobber：x9-x28 全部 + v/d8-v15（FP 序列可能用）
    clobbers = "".join(f', "{r}"' for r in REG_NAMES)
    clobbers += "".join(f', "v{i}"' for i in range(8, 16))

    # 载入/存回块用 x8r 作为 g_reg 基址（寄存器操作数 [regs]），
    # core 序列用 x8 作为 mem 基址（[base]）。两条基址都从输入操作数
    # 注入：gcc 会把 [regs] 和 [base] 分配到不同寄存器，我们用两条
    # mov 指令把它们各放入 x8r（临时寄存器，clobber 之）与 x8。
    # x8r 用 v30? 不行——用 x8 会冲突。方案：把 [regs] 先 mov 到
    # 一个专用 scratch：这里直接利用操作数编号（%0/%1），由 gcc 分配，
    # 载入/存回指令的操作数字段用 %[regs]/%[base] 原样注入。
    load_body = load_body.replace("x8r", "%[regs]")
    store_body = store_body.replace("x8r", "%[regs]")

    src = WRAPPER_TEMPLATE.format(
        seq_name=seq_name, n_lines=len(seq_lines), iters=iters,
        mem_bytes=mem_bytes, nregs=n, xs1=seed1, xs2=seed2,
        wb=M5_WORKBEGIN, we=M5_WORKEND,
        load_body=load_body, asm_body=asm_body, store_body=store_body,
        clobbers=clobbers,
    )
    if checker:
        # SDC-ED Task 7.1 deployment arm: same core sequence, two passes
        # over shadow channels, self-comparison epilogue (no golden).
        src = CHECKER_TEMPLATE.format(
            seq_name=seq_name, n_lines=len(seq_lines), iters=iters,
            mem_bytes=mem_bytes, nregs=n, xs1=seed1, xs2=seed2,
            wb=M5_WORKBEGIN, we=M5_WORKEND,
            load_body=load_body, asm_body=asm_body, store_body=store_body,
            clobbers=clobbers,
        )
    c_path = out_path + ".c"
    with open(c_path, "w") as f:
        f.write(src)
    cc_cmd = ["gcc", "-static", "-O2"]
    cc_cmd += ["-DWITH_M5OPS=1"] if with_m5ops else ["-DWITH_M5OPS=0"]
    cc_cmd += ["-o", out_path, c_path]
    r = subprocess.run(cc_cmd, capture_output=True, text=True, timeout=120)
    if r.returncode != 0:
        sys.exit(f"ERROR: gcc failed:\n{r.stderr}\n(wrapper kept at {c_path})")
    return out_path, c_path


def load_sequence(path):
    """从 .S/.txt 读指令序列（每行一条）。返回 (lines, errors)。"""
    lines, errors = [], []
    with open(path) as f:
        for i, raw in enumerate(f, 1):
            s, err = sanitize_asm_line(raw, i)
            if err:
                errors.append(err)
            elif s:
                lines.append(s)
    return lines, errors


def main():
    ap = argparse.ArgumentParser(description="Harpocrates sequence wrapper")
    ap.add_argument("--seq", help="输入：.S/.txt 指令序列 或 现成 ELF")
    ap.add_argument("--pass-through", action="store_true",
                    help="--seq 是现成 aarch64 ELF：直接复制到 --out")
    ap.add_argument("--out", required=True, help="输出 ELF 路径")
    ap.add_argument("--random", action="store_true",
                    help="生成随机序列（论文 Generator 第 0 代）")
    ap.add_argument("--n-inst", type=int, default=1000,
                    help="随机序列指令数（论文 IRF=10K/FU=5K/L1D=30K）")
    ap.add_argument("--mix", default="int-heavy",
                    choices=list(INST_POOL.keys()))
    ap.add_argument("--seed", type=int, default=20260916,
                    help="随机序列种子（确定性要求）")
    ap.add_argument("--mem-bytes", type=int, default=32 * 1024,
                    help="内存区域（默认 32KB=L1D，论文 L1D 协议）")
    ap.add_argument("--iters", type=int, default=1,
                    help="核心序列循环次数")
    ap.add_argument("--reg-seed1", type=lambda x: int(x, 0),
                    default=0x9510D3BF1AA8D548,
                    help="寄存器初值 xorshift 种子1（Task 7.3 变体用）")
    ap.add_argument("--reg-seed2", type=lambda x: int(x, 0),
                    default=0xA5C11881A68E546E,
                    help="寄存器初值 xorshift 种子2")
    ap.add_argument("--no-m5ops", action="store_true",
                    help="编译期去掉 ROI 标记（本机可跑；SUM/CRC 应与 "
                         "gem5 版一致，用于快速确定性验证）")
    ap.add_argument("--checker", action="store_true",
                    help="SDC-ED Task 7.1 部署模式：核心序列跑两遍"
                         "（影子通道），自比对输出 CHECKER=OK/FAIL"
                         "（无 golden——deployment-detection 臂）")
    args = ap.parse_args()

    if not args.seq and not args.random:
        ap.error("需要 --seq 或 --random 之一")

    if args.pass_through:
        if not args.seq or not os.path.isfile(args.seq):
            sys.exit("ERROR: --pass-through 需要存在的 --seq ELF")
        out = args.out
        if os.path.isdir(out):
            out = os.path.join(out, os.path.basename(args.seq))
        subprocess.run(["cp", args.seq, out], check=True)
        r = subprocess.run(["file", out], capture_output=True, text=True)
        print(f"pass-through: {r.stdout.strip()}")
        print(f"ELF: {out}")
        return 0

    if args.random:
        import random as _r
        rng = _r.Random(args.seed)
        lines = gen_random_sequence(args.n_inst, args.mix, rng)
        seq_name = f"random-{args.mix}-n{args.n_inst}-s{args.seed}"
    else:
        lines, errors = load_sequence(args.seq)
        if errors:
            print("ERROR: sequence sanitization failed:", file=sys.stderr)
            for e in errors:
                print("  " + e, file=sys.stderr)
            return 1
        if not lines:
            sys.exit("ERROR: empty sequence")
        seq_name = os.path.basename(args.seq)

    if args.mem_bytes < 64:
        sys.exit("ERROR: --mem-bytes too small")

    elf, c = wrap_and_compile(lines, args.out, seq_name, args.mem_bytes,
                              args.iters, args.reg_seed1, args.reg_seed2,
                              with_m5ops=not args.no_m5ops,
                              checker=args.checker)
    r = subprocess.run(["file", elf], capture_output=True, text=True)
    print(f"wrapped {len(lines)} lines (iters={args.iters}) -> {elf}")
    print(f"  {r.stdout.strip()}")
    print(f"  wrapper C: {c}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
